// PDF Export Utility for ExamForge
// Uses client-side PDF generation with html2pdf

export const exportExamToPDF = (exam, questions) => {
  try {
    // Check if html2pdf is available
    if (typeof html2pdf === 'undefined') {
      console.warn('html2pdf library not loaded. Add to index.html: <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>');
      alert('PDF export requires html2pdf library. Please refresh the page.');
      return;
    }

    const content = generateExamHTML(exam, questions);
    const element = document.createElement('div');
    element.innerHTML = content;
    
    const opt = {
      margin: 10,
      filename: `${exam.title.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { orientation: 'portrait', unit: 'mm', format: 'a4' }
    };

    html2pdf().set(opt).from(element).save();
  } catch (error) {
    console.error('PDF export error:', error);
    alert('Failed to export PDF: ' + error.message);
  }
};

export const generateExamHTML = (exam, questions) => {
  const currentDate = new Date().toLocaleDateString();
  const questionsHTML = questions.map((q, idx) => `
    <div style="page-break-inside: avoid; margin-bottom: 20px; padding-bottom: 15px; border-bottom: 1px solid #eee;">
      <div style="margin-bottom: 10px;">
        <strong style="color: #2a9d8f; font-size: 14px;">Q${idx + 1}.</strong>
        <span style="font-size: 14px; margin-left: 10px;">${q.question || q.q}</span>
      </div>
      ${q.opts ? `
        <div style="margin-left: 20px; margin-bottom: 10px;">
          ${q.opts.map((opt, i) => `
            <div style="margin: 5px 0; font-size: 13px;">
              <strong>${String.fromCharCode(65 + i)}.</strong> ${opt}
            </div>
          `).join('')}
        </div>
      ` : ''}
      ${q.correctAnswer ? `
        <div style="margin-left: 20px; color: #666; font-size: 12px; font-style: italic;">
          <strong>Expected Answer:</strong> ${q.correctAnswer}
        </div>
      ` : ''}
    </div>
  `).join('');

  return `
    <div style="font-family: Arial, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px;">
      <!-- Header -->
      <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid #2a9d8f; padding-bottom: 20px;">
        <h1 style="color: #2a9d8f; margin: 0 0 10px 0; font-size: 28px;">ExamForge</h1>
        <h2 style="color: #333; margin: 0 0 15px 0; font-size: 20px;">${exam.title || exam.subject + ' ' + exam.difficulty + ' Test'}</h2>
        <div style="color: #666; font-size: 14px;">
          <p style="margin: 5px 0;">
            <strong>Subject:</strong> ${exam.subject} | 
            <strong>Difficulty:</strong> ${exam.difficulty} | 
            <strong>Type:</strong> ${exam.type}
          </p>
          <p style="margin: 5px 0;">
            <strong>Total Questions:</strong> ${questions.length} | 
            <strong>Time Limit:</strong> ${exam.time} minutes | 
            <strong>Generated:</strong> ${currentDate}
          </p>
        </div>
      </div>

      <!-- Instructions -->
      <div style="background-color: #f0f7ff; border-left: 4px solid #2a9d8f; padding: 15px; margin-bottom: 30px;">
        <h3 style="color: #2a9d8f; margin-top: 0;">Instructions:</h3>
        <ul style="margin: 10px 0; padding-left: 20px; color: #333;">
          <li>Read each question carefully before answering.</li>
          <li>Answers are provided at the end of this document.</li>
          <li>This is a ${exam.type} format exam.</li>
          <li>${exam.time} minutes are allocated for this exam.</li>
          <li>Answer all questions to the best of your ability.</li>
        </ul>
      </div>

      <!-- Questions -->
      <div style="margin-bottom: 40px;">
        <h3 style="color: #2a9d8f; border-bottom: 2px solid #2a9d8f; padding-bottom: 10px;">Questions</h3>
        ${questionsHTML}
      </div>

      <!-- Footer -->
      <div style="text-align: center; color: #999; font-size: 12px; margin-top: 40px; border-top: 1px solid #eee; padding-top: 20px;">
        <p>Generated by ExamForge - AI-Powered Exam Preparation Platform</p>
        <p>Date: ${currentDate}</p>
      </div>
    </div>
  `;
};

// For backend PDF generation using pdfkit
export const generatePDFOptions = {
  format: 'A4',
  margin: { top: 20, bottom: 20, left: 20, right: 20 }
};
